/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminUser implements Serializable {

	private static final long serialVersionUID = -621092556;

	private Integer id;
	private Integer companyId;
	private String  username;
	private String  firstname;
	private String  lastname;
	private String  email;
	private String  phone;

	public AdminUser() {}

	public AdminUser(AdminUser value) {
		this.id = value.id;
		this.companyId = value.companyId;
		this.username = value.username;
		this.firstname = value.firstname;
		this.lastname = value.lastname;
		this.email = value.email;
		this.phone = value.phone;
	}

	public AdminUser(
		Integer id,
		Integer companyId,
		String  username,
		String  firstname,
		String  lastname,
		String  email,
		String  phone
	) {
		this.id = id;
		this.companyId = companyId;
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("AdminUser (");

		sb.append(id);
		sb.append(", ").append(companyId);
		sb.append(", ").append(username);
		sb.append(", ").append(firstname);
		sb.append(", ").append(lastname);
		sb.append(", ").append(email);
		sb.append(", ").append(phone);

		sb.append(")");
		return sb.toString();
	}
}
