/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

	private static final long serialVersionUID = -378282332;

	private Integer id;
	private String  companyName;
	private String  domain;

	public Company() {}

	public Company(Company value) {
		this.id = value.id;
		this.companyName = value.companyName;
		this.domain = value.domain;
	}

	public Company(
		Integer id,
		String  companyName,
		String  domain
	) {
		this.id = id;
		this.companyName = companyName;
		this.domain = domain;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Company (");

		sb.append(id);
		sb.append(", ").append(companyName);
		sb.append(", ").append(domain);

		sb.append(")");
		return sb.toString();
	}
}
