/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Instructor implements Serializable {

	private static final long serialVersionUID = -823379169;

	private final Integer id;
	private final String  firstName;
	private final String  lastName;
	private final Date    createdOn;
	private final String  email;
	private final String  active;
	private final String  gender;
	private final String  primaryPhone;
	private final String  secondaryPhone;
	private final String  addressLine1;
	private final String  addressLine2;
	private final String  city;
	private final String  state;
	private final String  zipcode;
	private final Date    certificationDate;
	private final Integer companyId;

	public Instructor(Instructor value) {
		this.id = value.id;
		this.firstName = value.firstName;
		this.lastName = value.lastName;
		this.createdOn = value.createdOn;
		this.email = value.email;
		this.active = value.active;
		this.gender = value.gender;
		this.primaryPhone = value.primaryPhone;
		this.secondaryPhone = value.secondaryPhone;
		this.addressLine1 = value.addressLine1;
		this.addressLine2 = value.addressLine2;
		this.city = value.city;
		this.state = value.state;
		this.zipcode = value.zipcode;
		this.certificationDate = value.certificationDate;
		this.companyId = value.companyId;
	}

	public Instructor(
		Integer id,
		String  firstName,
		String  lastName,
		Date    createdOn,
		String  email,
		String  active,
		String  gender,
		String  primaryPhone,
		String  secondaryPhone,
		String  addressLine1,
		String  addressLine2,
		String  city,
		String  state,
		String  zipcode,
		Date    certificationDate,
		Integer companyId
	) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.createdOn = createdOn;
		this.email = email;
		this.active = active;
		this.gender = gender;
		this.primaryPhone = primaryPhone;
		this.secondaryPhone = secondaryPhone;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.certificationDate = certificationDate;
		this.companyId = companyId;
	}

	public Integer getId() {
		return this.id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public String getEmail() {
		return this.email;
	}

	public String getActive() {
		return this.active;
	}

	public String getGender() {
		return this.gender;
	}

	public String getPrimaryPhone() {
		return this.primaryPhone;
	}

	public String getSecondaryPhone() {
		return this.secondaryPhone;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public String getState() {
		return this.state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public Date getCertificationDate() {
		return this.certificationDate;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Instructor (");

		sb.append(id);
		sb.append(", ").append(firstName);
		sb.append(", ").append(lastName);
		sb.append(", ").append(createdOn);
		sb.append(", ").append(email);
		sb.append(", ").append(active);
		sb.append(", ").append(gender);
		sb.append(", ").append(primaryPhone);
		sb.append(", ").append(secondaryPhone);
		sb.append(", ").append(addressLine1);
		sb.append(", ").append(addressLine2);
		sb.append(", ").append(city);
		sb.append(", ").append(state);
		sb.append(", ").append(zipcode);
		sb.append(", ").append(certificationDate);
		sb.append(", ").append(companyId);

		sb.append(")");
		return sb.toString();
	}
}
