/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstructionSession implements Serializable {

	private static final long serialVersionUID = 1426572062;

	private Integer   id;
	private Integer   studentId;
	private Integer   coursePackageId;
	private Integer   priceOverride;
	private Integer   paymentReceived;
	private Timestamp sessionDatetime;
	private Integer   companyId;
	private Integer   instructorId;
	private Date      createdOn;
	private Integer   createdBy;

	public InstructionSession() {}

	public InstructionSession(InstructionSession value) {
		this.id = value.id;
		this.studentId = value.studentId;
		this.coursePackageId = value.coursePackageId;
		this.priceOverride = value.priceOverride;
		this.paymentReceived = value.paymentReceived;
		this.sessionDatetime = value.sessionDatetime;
		this.companyId = value.companyId;
		this.instructorId = value.instructorId;
		this.createdOn = value.createdOn;
		this.createdBy = value.createdBy;
	}

	public InstructionSession(
		Integer   id,
		Integer   studentId,
		Integer   coursePackageId,
		Integer   priceOverride,
		Integer   paymentReceived,
		Timestamp sessionDatetime,
		Integer   companyId,
		Integer   instructorId,
		Date      createdOn,
		Integer   createdBy
	) {
		this.id = id;
		this.studentId = studentId;
		this.coursePackageId = coursePackageId;
		this.priceOverride = priceOverride;
		this.paymentReceived = paymentReceived;
		this.sessionDatetime = sessionDatetime;
		this.companyId = companyId;
		this.instructorId = instructorId;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Integer getCoursePackageId() {
		return this.coursePackageId;
	}

	public void setCoursePackageId(Integer coursePackageId) {
		this.coursePackageId = coursePackageId;
	}

	public Integer getPriceOverride() {
		return this.priceOverride;
	}

	public void setPriceOverride(Integer priceOverride) {
		this.priceOverride = priceOverride;
	}

	public Integer getPaymentReceived() {
		return this.paymentReceived;
	}

	public void setPaymentReceived(Integer paymentReceived) {
		this.paymentReceived = paymentReceived;
	}

	public Timestamp getSessionDatetime() {
		return this.sessionDatetime;
	}

	public void setSessionDatetime(Timestamp sessionDatetime) {
		this.sessionDatetime = sessionDatetime;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(Integer instructorId) {
		this.instructorId = instructorId;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InstructionSession (");

		sb.append(id);
		sb.append(", ").append(studentId);
		sb.append(", ").append(coursePackageId);
		sb.append(", ").append(priceOverride);
		sb.append(", ").append(paymentReceived);
		sb.append(", ").append(sessionDatetime);
		sb.append(", ").append(companyId);
		sb.append(", ").append(instructorId);
		sb.append(", ").append(createdOn);
		sb.append(", ").append(createdBy);

		sb.append(")");
		return sb.toString();
	}
}
