/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentEnrollment implements Serializable {

	private static final long serialVersionUID = 2140634541;

	private final Integer studentId;
	private final Integer coursePackageId;
	private final Integer priceOverride;
	private final Integer paymentReceived;
	private final Date    enrollmentDate;
	private final Date    completionDate;
	private final Integer companyId;
	private final Integer instructorId;

	public StudentEnrollment(StudentEnrollment value) {
		this.studentId = value.studentId;
		this.coursePackageId = value.coursePackageId;
		this.priceOverride = value.priceOverride;
		this.paymentReceived = value.paymentReceived;
		this.enrollmentDate = value.enrollmentDate;
		this.completionDate = value.completionDate;
		this.companyId = value.companyId;
		this.instructorId = value.instructorId;
	}

	public StudentEnrollment(
		Integer studentId,
		Integer coursePackageId,
		Integer priceOverride,
		Integer paymentReceived,
		Date    enrollmentDate,
		Date    completionDate,
		Integer companyId,
		Integer instructorId
	) {
		this.studentId = studentId;
		this.coursePackageId = coursePackageId;
		this.priceOverride = priceOverride;
		this.paymentReceived = paymentReceived;
		this.enrollmentDate = enrollmentDate;
		this.completionDate = completionDate;
		this.companyId = companyId;
		this.instructorId = instructorId;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public Integer getCoursePackageId() {
		return this.coursePackageId;
	}

	public Integer getPriceOverride() {
		return this.priceOverride;
	}

	public Integer getPaymentReceived() {
		return this.paymentReceived;
	}

	public Date getEnrollmentDate() {
		return this.enrollmentDate;
	}

	public Date getCompletionDate() {
		return this.completionDate;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public Integer getInstructorId() {
		return this.instructorId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("StudentEnrollment (");

		sb.append(studentId);
		sb.append(", ").append(coursePackageId);
		sb.append(", ").append(priceOverride);
		sb.append(", ").append(paymentReceived);
		sb.append(", ").append(enrollmentDate);
		sb.append(", ").append(completionDate);
		sb.append(", ").append(companyId);
		sb.append(", ").append(instructorId);

		sb.append(")");
		return sb.toString();
	}
}
