/**
 * This class is generated by jOOQ
 */
package com.dsmc.data;


import com.dsmc.data.tables.AdminUser;
import com.dsmc.data.tables.AuthCredential;
import com.dsmc.data.tables.Company;
import com.dsmc.data.tables.CoursePackage;
import com.dsmc.data.tables.Instructor;
import com.dsmc.data.tables.Student;
import com.dsmc.data.tables.StudentEnrollment;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1041512738;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.ADMIN_USER_ID_SEQ,
			Sequences.COMPANY_ID_SEQ,
			Sequences.COURSE_PACKAGE_ID_SEQ,
			Sequences.INSTRUCTOR_ID_SEQ,
			Sequences.STUDENT_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			AdminUser.ADMIN_USER,
			AuthCredential.AUTH_CREDENTIAL,
			Company.COMPANY,
			CoursePackage.COURSE_PACKAGE,
			Instructor.INSTRUCTOR,
			Student.STUDENT,
			StudentEnrollment.STUDENT_ENROLLMENT);
	}
}
