/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.records;


import com.dsmc.data.tables.Company;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = 615615820;

	/**
	 * Setter for <code>public.company.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.company.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.company.company_name</code>.
	 */
	public void setCompanyName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.company.company_name</code>.
	 */
	public String getCompanyName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.company.domain</code>.
	 */
	public void setDomain(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.company.domain</code>.
	 */
	public String getDomain() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Company.COMPANY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Company.COMPANY.COMPANY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Company.COMPANY.DOMAIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getCompanyName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDomain();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value2(String value) {
		setCompanyName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value3(String value) {
		setDomain(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompanyRecord
	 */
	public CompanyRecord() {
		super(Company.COMPANY);
	}

	/**
	 * Create a detached, initialised CompanyRecord
	 */
	public CompanyRecord(Integer id, String companyName, String domain) {
		super(Company.COMPANY);

		setValue(0, id);
		setValue(1, companyName);
		setValue(2, domain);
	}
}
