/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.records;


import com.dsmc.data.tables.CoursePackage;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoursePackageRecord extends UpdatableRecordImpl<CoursePackageRecord> implements Record9<Integer, Date, String, String, String, Integer, Date, Date, Integer> {

	private static final long serialVersionUID = -197902774;

	/**
	 * Setter for <code>public.course_package.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.course_package.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.course_package.created_on</code>.
	 */
	public void setCreatedOn(Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.course_package.created_on</code>.
	 */
	public Date getCreatedOn() {
		return (Date) getValue(1);
	}

	/**
	 * Setter for <code>public.course_package.active</code>.
	 */
	public void setActive(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.course_package.active</code>.
	 */
	public String getActive() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.course_package.name</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.course_package.name</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.course_package.description</code>.
	 */
	public void setDescription(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.course_package.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.course_package.price</code>.
	 */
	public void setPrice(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.course_package.price</code>.
	 */
	public Integer getPrice() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.course_package.start_date</code>.
	 */
	public void setStartDate(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.course_package.start_date</code>.
	 */
	public Date getStartDate() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>public.course_package.end_date</code>.
	 */
	public void setEndDate(Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.course_package.end_date</code>.
	 */
	public Date getEndDate() {
		return (Date) getValue(7);
	}

	/**
	 * Setter for <code>public.course_package.company_id</code>.
	 */
	public void setCompanyId(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.course_package.company_id</code>.
	 */
	public Integer getCompanyId() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Date, String, String, String, Integer, Date, Date, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Date, String, String, String, Integer, Date, Date, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CoursePackage.COURSE_PACKAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field2() {
		return CoursePackage.COURSE_PACKAGE.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CoursePackage.COURSE_PACKAGE.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CoursePackage.COURSE_PACKAGE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return CoursePackage.COURSE_PACKAGE.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return CoursePackage.COURSE_PACKAGE.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return CoursePackage.COURSE_PACKAGE.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field8() {
		return CoursePackage.COURSE_PACKAGE.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return CoursePackage.COURSE_PACKAGE.COMPANY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value2() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value8() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getCompanyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value2(Date value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value3(String value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value5(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value6(Integer value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value7(Date value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value8(Date value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord value9(Integer value) {
		setCompanyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackageRecord values(Integer value1, Date value2, String value3, String value4, String value5, Integer value6, Date value7, Date value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CoursePackageRecord
	 */
	public CoursePackageRecord() {
		super(CoursePackage.COURSE_PACKAGE);
	}

	/**
	 * Create a detached, initialised CoursePackageRecord
	 */
	public CoursePackageRecord(Integer id, Date createdOn, String active, String name, String description, Integer price, Date startDate, Date endDate, Integer companyId) {
		super(CoursePackage.COURSE_PACKAGE);

		setValue(0, id);
		setValue(1, createdOn);
		setValue(2, active);
		setValue(3, name);
		setValue(4, description);
		setValue(5, price);
		setValue(6, startDate);
		setValue(7, endDate);
		setValue(8, companyId);
	}
}
