/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.records;


import com.dsmc.data.tables.Student;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record16<Integer, String, String, Date, String, String, String, String, String, String, String, String, String, String, Date, Integer> {

	private static final long serialVersionUID = -518445638;

	/**
	 * Setter for <code>public.student.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.student.first_name</code>.
	 */
	public void setFirstName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.student.last_name</code>.
	 */
	public void setLastName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.student.created_on</code>.
	 */
	public void setCreatedOn(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student.created_on</code>.
	 */
	public Date getCreatedOn() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>public.student.email</code>.
	 */
	public void setEmail(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.student.email</code>.
	 */
	public String getEmail() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.student.active</code>.
	 */
	public void setActive(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.student.active</code>.
	 */
	public String getActive() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.student.gender</code>.
	 */
	public void setGender(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.student.gender</code>.
	 */
	public String getGender() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.student.primary_phone</code>.
	 */
	public void setPrimaryPhone(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.student.primary_phone</code>.
	 */
	public String getPrimaryPhone() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.student.secondary_phone</code>.
	 */
	public void setSecondaryPhone(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.student.secondary_phone</code>.
	 */
	public String getSecondaryPhone() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.student.address_line1</code>.
	 */
	public void setAddressLine1(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.student.address_line1</code>.
	 */
	public String getAddressLine1() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.student.address_line2</code>.
	 */
	public void setAddressLine2(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.student.address_line2</code>.
	 */
	public String getAddressLine2() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>public.student.city</code>.
	 */
	public void setCity(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.student.city</code>.
	 */
	public String getCity() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>public.student.state</code>.
	 */
	public void setState(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.student.state</code>.
	 */
	public String getState() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>public.student.zipcode</code>.
	 */
	public void setZipcode(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.student.zipcode</code>.
	 */
	public String getZipcode() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>public.student.dob</code>.
	 */
	public void setDob(Date value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.student.dob</code>.
	 */
	public Date getDob() {
		return (Date) getValue(14);
	}

	/**
	 * Setter for <code>public.student.company_id</code>.
	 */
	public void setCompanyId(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>public.student.company_id</code>.
	 */
	public Integer getCompanyId() {
		return (Integer) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, String, String, Date, String, String, String, String, String, String, String, String, String, String, Date, Integer> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, String, String, Date, String, String, String, String, String, String, String, String, String, String, Date, Integer> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Student.STUDENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Student.STUDENT.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Student.STUDENT.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return Student.STUDENT.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Student.STUDENT.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Student.STUDENT.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Student.STUDENT.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Student.STUDENT.PRIMARY_PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Student.STUDENT.SECONDARY_PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Student.STUDENT.ADDRESS_LINE1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Student.STUDENT.ADDRESS_LINE2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Student.STUDENT.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return Student.STUDENT.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return Student.STUDENT.ZIPCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field15() {
		return Student.STUDENT.DOB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return Student.STUDENT.COMPANY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getPrimaryPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSecondaryPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getAddressLine1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getAddressLine2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getZipcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value15() {
		return getDob();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getCompanyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value2(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value3(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value4(Date value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value5(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value6(String value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value7(String value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value8(String value) {
		setPrimaryPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value9(String value) {
		setSecondaryPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value10(String value) {
		setAddressLine1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value11(String value) {
		setAddressLine2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value12(String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value13(String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value14(String value) {
		setZipcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value15(Date value) {
		setDob(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value16(Integer value) {
		setCompanyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord values(Integer value1, String value2, String value3, Date value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Date value15, Integer value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentRecord
	 */
	public StudentRecord() {
		super(Student.STUDENT);
	}

	/**
	 * Create a detached, initialised StudentRecord
	 */
	public StudentRecord(Integer id, String firstName, String lastName, Date createdOn, String email, String active, String gender, String primaryPhone, String secondaryPhone, String addressLine1, String addressLine2, String city, String state, String zipcode, Date dob, Integer companyId) {
		super(Student.STUDENT);

		setValue(0, id);
		setValue(1, firstName);
		setValue(2, lastName);
		setValue(3, createdOn);
		setValue(4, email);
		setValue(5, active);
		setValue(6, gender);
		setValue(7, primaryPhone);
		setValue(8, secondaryPhone);
		setValue(9, addressLine1);
		setValue(10, addressLine2);
		setValue(11, city);
		setValue(12, state);
		setValue(13, zipcode);
		setValue(14, dob);
		setValue(15, companyId);
	}
}
