/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables.records;


import com.dsmc.data.tables.StudentEnrollment;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentEnrollmentRecord extends TableRecordImpl<StudentEnrollmentRecord> implements Record8<Integer, Integer, Integer, Integer, Date, Date, Integer, Integer> {

	private static final long serialVersionUID = 1784737784;

	/**
	 * Setter for <code>public.student_enrollment.student_id</code>.
	 */
	public void setStudentId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.student_id</code>.
	 */
	public Integer getStudentId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.student_enrollment.course_package_id</code>.
	 */
	public void setCoursePackageId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.course_package_id</code>.
	 */
	public Integer getCoursePackageId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.student_enrollment.price_override</code>.
	 */
	public void setPriceOverride(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.price_override</code>.
	 */
	public Integer getPriceOverride() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.student_enrollment.payment_received</code>.
	 */
	public void setPaymentReceived(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.payment_received</code>.
	 */
	public Integer getPaymentReceived() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.student_enrollment.enrollment_date</code>.
	 */
	public void setEnrollmentDate(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.enrollment_date</code>.
	 */
	public Date getEnrollmentDate() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>public.student_enrollment.completion_date</code>.
	 */
	public void setCompletionDate(Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.completion_date</code>.
	 */
	public Date getCompletionDate() {
		return (Date) getValue(5);
	}

	/**
	 * Setter for <code>public.student_enrollment.company_id</code>.
	 */
	public void setCompanyId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.company_id</code>.
	 */
	public Integer getCompanyId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.student_enrollment.instructor_id</code>.
	 */
	public void setInstructorId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.student_enrollment.instructor_id</code>.
	 */
	public Integer getInstructorId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, Date, Date, Integer, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, Date, Date, Integer, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return StudentEnrollment.STUDENT_ENROLLMENT.STUDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return StudentEnrollment.STUDENT_ENROLLMENT.COURSE_PACKAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return StudentEnrollment.STUDENT_ENROLLMENT.PRICE_OVERRIDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return StudentEnrollment.STUDENT_ENROLLMENT.PAYMENT_RECEIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return StudentEnrollment.STUDENT_ENROLLMENT.ENROLLMENT_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field6() {
		return StudentEnrollment.STUDENT_ENROLLMENT.COMPLETION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return StudentEnrollment.STUDENT_ENROLLMENT.COMPANY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return StudentEnrollment.STUDENT_ENROLLMENT.INSTRUCTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getStudentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getCoursePackageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPriceOverride();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPaymentReceived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getEnrollmentDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value6() {
		return getCompletionDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getCompanyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getInstructorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value1(Integer value) {
		setStudentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value2(Integer value) {
		setCoursePackageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value3(Integer value) {
		setPriceOverride(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value4(Integer value) {
		setPaymentReceived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value5(Date value) {
		setEnrollmentDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value6(Date value) {
		setCompletionDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value7(Integer value) {
		setCompanyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord value8(Integer value) {
		setInstructorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentEnrollmentRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Date value5, Date value6, Integer value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentEnrollmentRecord
	 */
	public StudentEnrollmentRecord() {
		super(StudentEnrollment.STUDENT_ENROLLMENT);
	}

	/**
	 * Create a detached, initialised StudentEnrollmentRecord
	 */
	public StudentEnrollmentRecord(Integer studentId, Integer coursePackageId, Integer priceOverride, Integer paymentReceived, Date enrollmentDate, Date completionDate, Integer companyId, Integer instructorId) {
		super(StudentEnrollment.STUDENT_ENROLLMENT);

		setValue(0, studentId);
		setValue(1, coursePackageId);
		setValue(2, priceOverride);
		setValue(3, paymentReceived);
		setValue(4, enrollmentDate);
		setValue(5, completionDate);
		setValue(6, companyId);
		setValue(7, instructorId);
	}
}
