/**
 * This class is generated by jOOQ
 */
package com.dsmc.data.tables;


import com.dsmc.data.Keys;
import com.dsmc.data.Public;
import com.dsmc.data.tables.records.CoursePackageRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoursePackage extends TableImpl<CoursePackageRecord> {

	private static final long serialVersionUID = 1004126948;

	/**
	 * The reference instance of <code>public.course_package</code>
	 */
	public static final CoursePackage COURSE_PACKAGE = new CoursePackage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CoursePackageRecord> getRecordType() {
		return CoursePackageRecord.class;
	}

	/**
	 * The column <code>public.course_package.id</code>.
	 */
	public final TableField<CoursePackageRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.course_package.created_on</code>.
	 */
	public final TableField<CoursePackageRecord, Date> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.course_package.active</code>.
	 */
	public final TableField<CoursePackageRecord, String> ACTIVE = createField("active", org.jooq.impl.SQLDataType.CHAR.length(1).defaulted(true), this, "");

	/**
	 * The column <code>public.course_package.name</code>.
	 */
	public final TableField<CoursePackageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(150).defaulted(true), this, "");

	/**
	 * The column <code>public.course_package.description</code>.
	 */
	public final TableField<CoursePackageRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.course_package.price</code>.
	 */
	public final TableField<CoursePackageRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.course_package.start_date</code>.
	 */
	public final TableField<CoursePackageRecord, Date> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.course_package.end_date</code>.
	 */
	public final TableField<CoursePackageRecord, Date> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.course_package.company_id</code>.
	 */
	public final TableField<CoursePackageRecord, Integer> COMPANY_ID = createField("company_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.course_package</code> table reference
	 */
	public CoursePackage() {
		this("course_package", null);
	}

	/**
	 * Create an aliased <code>public.course_package</code> table reference
	 */
	public CoursePackage(String alias) {
		this(alias, COURSE_PACKAGE);
	}

	private CoursePackage(String alias, Table<CoursePackageRecord> aliased) {
		this(alias, aliased, null);
	}

	private CoursePackage(String alias, Table<CoursePackageRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CoursePackageRecord, Integer> getIdentity() {
		return Keys.IDENTITY_COURSE_PACKAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CoursePackageRecord> getPrimaryKey() {
		return Keys.COURSE_PACKAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CoursePackageRecord>> getKeys() {
		return Arrays.<UniqueKey<CoursePackageRecord>>asList(Keys.COURSE_PACKAGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<CoursePackageRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<CoursePackageRecord, ?>>asList(Keys.COURSE_PACKAGE__COURSE_PACKAGE_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CoursePackage as(String alias) {
		return new CoursePackage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CoursePackage rename(String name) {
		return new CoursePackage(name, null);
	}
}
